### ISSUE TITLE
transparent icons show overlapping internal shapes

### ISSUE THREAD

**Issue by danawoodman** [lucide-icons/lucide#2136]
### Package

- [X] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [X] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.378.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [ ] Chrome/Chromium
- [X] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

If you add an opacity less than 1.0 for an icon, you will start to see the internal shapes of the icons. You can see this on the Lucide site itself in the small previews of the icons by zooming in using your browser

It seems that icons should be pre-processed to flatten/merge all shapes rather than shipping versions of the icons with the individual overlapping shape components

<img width="378" alt="image" src="https://github.com/lucide-icons/lucide/assets/157695/10e52142-2a19-45e3-b06b-5d183d6cc2f9">

<img width="387" alt="image" src="https://github.com/lucide-icons/lucide/assets/157695/6d8c9c34-18ee-45ba-aea9-d11252d30a10">

<img width="371" alt="image" src="https://github.com/lucide-icons/lucide/assets/157695/cb8484f2-ab57-4bf1-ac16-979e6ffef039">

### Steps to reproduce

1. Go to any icon on the Lucide site
2. Click see in action
3. Increase stroke width
4. Zoom in on icon

Link to a video: https://a.cl.ly/eDuKop7L

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by jguddas** [comment]
Solved by #2135

**Comment by danawoodman** [comment]
awesome! looks like i was just a bit late to the game on this one but glad its being addressed!

**Comment by Plonq** [comment]
#2135 was closed without merging. What is the proper solution to this?

**Comment by glebec** [comment]
Unfortunately #2135 was closed without an obvious plan for remediation, so this remains an issue with Lucide icons. This is forcing me to rethink some fundamental principles of my design system since now I can't let icons inherit slightly-translucent text colors (which are designed to blend harmoniously with subtly-colored backgrounds), but instead need to define classes which separately apply color and opacity props.

**Comment by ckizer** [comment]
This is still a problem today in my next.js project in 2025. Any solutions.

**Comment by alexsafayan** [comment]
also running into this

**Comment by alexsafayan** [comment]
same here

(bug) color overlap
```tsx
<ImageIcon className='size-20 text-black/70' />
```

![Image](https://github.com/user-attachments/assets/7ea16fd8-8c64-4e0f-9ca6-449e29344b0b)

(fix) use css opacity
```tsx
<ImageIcon className='size-20 text-black opacity-70' />
```

![Image](https://github.com/user-attachments/assets/af9a7af9-d4c5-4bdb-b34a-45fa24fa10d1)

_Originally posted by @GrahamQuan in https://github.com/lucide-icons/lucide/issues/2135#issuecomment-2702982160_
